version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:7474"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

    networks:
      - neo4j-network

  phone_tracker:
    build: ./phone_tracker
    container_name: phone_tracker
    ports:
      - "5000:5000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
    depends_on:
      - neo4j
        # condition: service_healthy
    networks:
      - neo4j-network

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:



networks:
  neo4j-network:
    driver: bridge
