version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/yourpassword  
    ports:
      - "7474:7474"  
      - "7687:7687"  #
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
    networks:
      - neo4j-network

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:

networks:
  neo4j-network:
    driver: bridge
